include:
- ./mqueue/__init__.py
- ./mqueue/mqueue.py
- ./mqueue/requirements.txt
- ./mqueue/build.sh
kind: ArchiveUploadSpec
name: mqueue---init---py-eQ56

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mqueue
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://mqueue---init---py-eQ56
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-12T05:56:57Z"
