include:
- ./harvester/__init__.py
- ./harvester/base.py
- ./harvester/refresh.py
- ./harvester/requirements.txt
- ./harvester/build.sh
kind: ArchiveUploadSpec
name: harvester---init---py-q8KN

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mharvesters
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://harvester---init---py-q8KN
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-12T05:09:55Z"
