apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: mqueue
spec:
  createingress: false
  functionref:
    functionweights: null
    name: mqueue
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /mqueue/{topic}
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /mqueue/{topic}
