apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: perfretain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  availability: melbourne-qh2-uom
  type: performance
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain


